[server]
url = "0.0.0.0"
port = 8082

[database]
url= "mongodb+srv://tonyqihuanyang:F7LY36fwvIXM6VDx@cluster0.mczne.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
database_name = "markdown-pro"